### ISSUE TITLE
login in problem

### ISSUE THREAD

**Issue by sleiman23** [ed-roh/MERNSocialMedia#56]

**Comment by sleiman23** [comment]
act-dom.development.js:18687 The above error occurred in the <PostWidget> component:

    at PostWidget (http://localhost:3000/static/js/bundle.js:3120:5)
    at div
    at http://localhost:3000/static/js/bundle.js:4345:66
    at Box (http://localhost:3000/static/js/bundle.js:22128:72)
    at div
    at http://localhost:3000/static/js/bundle.js:4345:66
    at Box (http://localhost:3000/static/js/bundle.js:22128:72)
    at div
    at http://localhost:3000/static/js/bundle.js:4345:66
    at Box (http://localhost:3000/static/js/bundle.js:22128:72)
    at HomePage (http://localhost:3000/static/js/bundle.js:714:87)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:73364:5)
    at Routes (http://localhost:3000/static/js/bundle.js:73854:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:20961:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:21346:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:19410:14)
    at Router (http://localhost:3000/static/js/bundle.js:73792:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:71981:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:45:72)
    at PersistGate (http://localhost:3000/static/js/bundle.js:80262:5)
    at Provider (http://localhost:3000/static/js/bundle.js:69310:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
here also a part of the error

**Comment by Anshv99** [comment]
i am facing login problem when i click on login button it gives me 500 internal sever error. when i used postman to see what went wrong it says
 {
  "error": "data and hash arguments required"
}
i think the password or the user.password in line 50 of auth.js in controllers is giving this error

**Comment by piyushk2000** [comment]
actualy this is because you have not set JWT in .env file make sure to set that and it will work

**Comment by rakistazecho7** [comment]
> actualy this is because you have not set JWT in .env file make sure to set that and it will work

what do you mean bro, I have the same problem

**Comment by killerTiger10** [comment]
in .env file, you need to describe variable like:
JWT=jkbadkkvahd 
that will be used as the secret key for the token you are using in login.

**Comment by piyushk2000** [comment]
> > actualy this is because you have not set JWT in .env file make sure to set that and it will work
> 
> what do you mean bro, I have the same problem

Create an .env file, put JWT='xyz'
