### ISSUE TITLE
posts.map is not a function in the file PostsWidget

### ISSUE THREAD

**Issue by danishbinasmath** [ed-roh/MERNSocialMedia#73]
ERROR
posts.map is not a function
TypeError: posts.map is not a function
    at PostsWidget (http://localhost:3000/static/js/bundle.js:5338:21)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:60156:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:63442:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:64738:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:49748:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:49792:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:49849:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:69723:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:68970:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:68893:9)

**Comment by Mohammad-Alnusairat** [comment]
Array.from(posts).map

**Comment by SammitBadodekar** [comment]
is this issue still open ?
